function_version: '1.0.0'
organization: YourOrg

# Update LOC to your location
location_name: LOC

# specify the name of the source making it possible to identify where the data originates from, ex: 'workmate', 'sap', 'oracle',..
# Update SOURCE to your source
source_name: SOURCE
files_dataset: ingestion

schemaSpace: cdf_cdm
viewVersion: v1

functionClientId: ${IDP_CLIENT_ID}
functionClientSecret: ${IDP_CLIENT_SECRET}
functionVersion: 'v1'

workflow: key_extraction_aliasing

# source ID from Azure AD for the corresponding groups, ex 'c74797ce-9191-4a4a-9186-8fe21c54c3de'
files_location_processing_group_source_id: 90af3183-cf62-408f-ae4c-f078cbf0e1f8
